table! {
    use diesel::sql_types::*;
    use crate::db::enums::*;

    /// Representation of the `todo` table.
    ///
    /// (Automatically generated by Diesel.)
    todo (id) {
        /// The `id` column of the `todo` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `todo` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `body` column of the `todo` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Text,
        /// The `time_modified` column of the `todo` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        time_modified -> Nullable<Timestamp>,
        /// The `completed` column of the `todo` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        completed -> Bool,
        /// The `media` column of the `todo` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        media -> Nullable<Text>,
        /// The `parent_id` column of the `todo` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        parent_id -> Int4,
        /// The `parent_name` column of the `todo` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        parent_name -> Text,
    }
}
